### DISCUSSION TITLE
Pretalx standalone docker-compose for trialing the software

### DISCUSSION THREAD

**Discussion by nktnet1** [pretalx/pretalx#1950] [General]
For anyone looking to trial the software, I was able to get it up and running with the single compose file below:

```yaml
services:
  pretalx:
    image: pretalx/standalone:latest
    ports:
      - "8000:80"
    environment:
      - PRETALX_SITE_NAME=Your Conference Name
      - PRETALX_SITE_URL=http://localhost:8000
```

Instructions:
1. Make an empty directory and copy the compose file to it. Make sure to `cd` into the directory
2. Run `docker compose up` in one terminal
3. Open another terminal and run `docker compose exec pretalx pretalx init`, answering all questions in the prompts
4. Open `http://localhost:8000`. 

---

To instead use pretalx with postgres and redis, here's a more advance docker-compose (although I believe there might currently be a problem with postgres environment variables + frontend as [noted below](https://github.com/pretalx/pretalx/discussions/1950#discussioncomment-12088604)):

**UPDATE**: issue above will be resolved when this is merged: https://github.com/pretalx/pretalx-docker/pull/63

```yaml
services:
  pretalx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes: 
      - pretalx_data:/data
      - pretalx_public_data:/public
    environment:
      # App
      - PRETALX_SITE_NAME=${PRETALX_SITE_NAME}
      - PRETALX_SITE_URL=${PRETALX_SITE_URL}
      - PRETALX_CONFIG_FILE=/dev/null
      - PRETALX_DEBUG=True
      # Database
      - PRETALX_DB_TYPE=postgresql
      - PRETALX_DB_HOST=pretalx_postgres
      - PRETALX_DB_PORT=5432
      - PRETALX_DB_NAME=${POSTGRES_DB}
      - PRETALX_DB_USER=${POSTGRES_USER}
      - PRETALX_DB_PASS=${POSTGRES_PASSWORD}
      # Cache
      - PRETALX_REDIS=redis://:${REDIS_PASSWORD}@pretalx_redis:6379/1
    depends_on:
      pretalx_postgres:
        condition: service_healthy
      pretalx_redis:
        condition: service_healthy

  pretalx_postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - pretalx_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pretalx_redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes: 
      - pretalx_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pretalx_data:
  pretalx_public_data:
  pretalx_postgres_data:
  pretalx_redis_data:
```

You will additionally need to set a `.env` file in the same directory, e.g.
```env
# App
PRETALX_SITE_NAME=Your Conference Name
PRETALX_SITE_URL=http://localhost:8000

# Database
POSTGRES_DB=pretalx
POSTGRES_USER=pretalx
POSTGRES_PASSWORD=46058991674e7ba9d690d2d64032df2a

# Cache
REDIS_PASSWORD=084761daef479a1102d38c2ed8a1f9c0
```

**Comment by rixx** [comment]
This might be cool to document in the [pretalx-docker repository](https://github.com/pretalx/pretalx-docker)!

**Reply by nktnet1** [reply]
Hey @rixx,

Thanks for the suggestion - I've made an issue in that repo.

On another note, I've updated my post to include both a sqlite version and a postgres version.
However, I believe there might be a **bug when it comes to using the frontend GUI with postgres environment variables**.

For example, assuming
- you're in a directory with a `docker-compose.yaml` and `.env` as shown for the postgres + redis version in my original post
- you've ran the command `docker compose exec pretalx pretalx init`, and registered a user, e.g. `admin@admin.com` with password `testpassword999`
Going to `http://localhost:8000`, any attempts to log in from the web interface will fail with
>  No user account matches the entered credentials. Are you sure that you typed your password correctly? 

Interestingly, I believe this is because the postgres environment variables are not registered correctly when using the frontend/GUI

---

To confirm the user was created successfully with the init command, here's the output when I check the postgres database:

<details close>
<summary>click to view logs</summary>

```sh
# From host machine, enter postgres database container
$ docker compose exec pretalx_postgres bash        
root@e5b22bf18489:/# psql -U pretalx
psql (17.2 (Debian 17.2-1.pgdg120+1))
Type "help" for help.

pretalx=# SELECT email, password FROM person_user;
      email      |                                                     password                                                     
-----------------+------------------------------------------------------------------------------------------------------------------
 admin@admin.com | argon2$argon2id$v=19$m=102400,t=2,p=8$MDlYTjNobUx6T2NOVzRWbHJteHFqUA$MBQ2Efdy6Oq2tuRFH47MDb5GPkXKPrtijH4tvc/ZYk0
(1 row)

pretalx=#
```

</details>

and similarly from the main app's container:

<details close>
<summary>click to view logs</summary>

```sh
# From host machine, enter pretalx container
$ docker compose exec pretalx pretalx shell
fatal: not a git repository (or any of the parent directories): .git
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.1                             ┃
┃ ┃  ┌─·──╮  ┃  Settings:                                     ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)               ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                         ┃
┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3             ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /pretalx/src/pretalx               ┃
┃     ╰─╯       DEVELOPMENT MODE, DO NOT USE IN PRODUCTION!   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Operations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, schedule, sessions, submission
Running migrations:
  No migrations to apply.
fatal: not a git repository (or any of the parent directories): .git
┏━━━━━━━━rations to perform:
  Apply all migrations: auth, authtoken, common, contenttypes, event, mail, person, schedule, sessions, submission
Running migrations:
  No migrations to apply.
fatal: not a git repository (or any of the parent directories): .git
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.1                             ┃
┃ ┃  ┌─·──╮  ┃  Settings:                                     ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)               ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                         ┃
┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3             ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /pretalx/src/pretalx               ┃
┃     ╰─╯       DEVELOPMENT MODE, DO NOT USE IN PRODUCTION!   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━━━━━━━━━━┓  pretalx v2024.3.1                             ┃
┃ ┃  ┌─·──╮  ┃  Settings:                                     ┃
┃ ┃  │  O │  ┃  Database:  pretalx (postgresql)               ┃
┃ ┃  │ ┌──╯  ┃  Logging:   /data/logs                         ┃
┃ ┃  └─┘     ┃  Python:    /usr/local/bin/python3             ┃
┃ ┗━━━┯━┯━━━━┛  Source:    /pretalx/src/pretalx               ┃
┃     ╰─╯       DEVELOPMENT MODE, DO NOT USE IN PRODUCTION!   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Python 3.10.15 (main, Oct 19 2024, 19:18:19) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.contrib.auth import authenticate
>>> user = authenticate(email="admin@admin.com", password="a")
>>> print(user)
Unnamed user
>>>
```

</details>

However, it appears that the frontend appears to still use the sqlite database.
For example, if I perform the following action to remove the sqlite database (which should've never been used in the first place):

<details close>
<summary>click to view logs</summary>

```sh
# From host machine, enter pretalx container
$ docker compose exec pretalx bash
pretalxuser@f773e5b62851:/$ ls -lA /data/
total 832
-rw------- 1 pretalxuser pretalxuser     50 Feb  7 01:14 .secret
-rw-r--r-- 1 pretalxuser pretalxuser 843776 Feb  7 01:14 db.sqlite3
drwxr-xr-x 1 pretalxuser pretalxuser      0 Feb  7 01:14 htmlexport
drwxr-xr-x 1 pretalxuser pretalxuser     22 Feb  7 01:14 logs
drwxr-xr-x 1 pretalxuser pretalxuser      0 Feb  7 01:14 media
pretalxuser@f773e5b62851:/$ rm -v /data/db.sqlite3
removed '/data/db.sqlite3'
```

</details>

and refresh the frontend, we now get:

![pretalx-500-error](https://github.com/user-attachments/assets/137f1a5d-e8ac-4e30-81c8-3805eb6fa51e)

---

Now, if instead of using environment variables, we create a minimal `./pretalx.cfg` config file:

```ini
[database]
backend = postgresql
name = pretalx
user = pretalx
password = 46058991674e7ba9d690d2d64032df2a
host = pretalx_postgres
port = 5432
```

and adding the following volume mount to the pretalx container:
```yaml
    volumes:
      - ./pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
```

it is now possible to log in using the frontend web interface. We can now also confirm that no `/data/db.sqlite3` files gets created:
<details close>
<summary>click to view logs</summary>

```sh
# From host machine, enter pretalx container
$ docker compose exec pretalx bash        
pretalxuser@15192b39c88f:/$ ls -lA /data/
total 4
-rw------- 1 pretalxuser pretalxuser 50 Feb  7 01:35 .secret
drwxr-xr-x 1 pretalxuser pretalxuser  0 Feb  7 01:35 htmlexport
drwxr-xr-x 1 pretalxuser pretalxuser 22 Feb  7 01:35 logs
drwxr-xr-x 1 pretalxuser pretalxuser  0 Feb  7 01:35 media
pretalxuser@15192b39c88f:/$ 
```

</details>

Are you able to help look into this?

**Reply by nktnet1** [reply]
Another interesting discovery - adding these two lines to the `pretalx` container seems to make it work:
```yaml
    entrypoint: ["python3", "/pretalx/src/manage.py"]
    command: ["runserver", "0.0.0.0:80"]
```

<details close>
<summary>click to view full docker-compose.yaml</summary>

```yaml
services:
  pretalx:
    image: pretalx/standalone:latest
    restart: unless-stopped

    # Make these changes:
    entrypoint: ["python3", "/pretalx/src/manage.py"]
    command: ["runserver", "0.0.0.0:80"]
 
    ports:
      - "8000:80"
    environment:
      # App
      - PRETALX_SITE_NAME=${PRETALX_SITE_NAME}
      - PRETALX_SITE_URL=${PRETALX_SITE_URL}
      - PRETALX_DEBUG=False
      # Database
      - PRETALX_DB_TYPE=postgresql
      - PRETALX_DB_HOST=pretalx_postgres
      - PRETALX_DB_PORT=5432
      - PRETALX_DB_NAME=${POSTGRES_DB}
      - PRETALX_DB_USER=${POSTGRES_USER}
      - PRETALX_DB_PASS=${POSTGRES_PASSWORD}
      # Cache
      - PRETALX_REDIS=redis://:${REDIS_PASSWORD}@pretalx_redis:6379/1
    depends_on:
      pretalx_postgres:
        condition: service_healthy
      pretalx_redis:
        condition: service_healthy

  pretalx_postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - pretalx_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pretalx_redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes: 
      - pretalx_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pretalx_postgres_data:
  pretalx_redis_data:
```

</details>

but the gunicorn server ran using `pretalx all` from the [standalone Dockerfile](https://github.com/pretalx/pretalx-docker/blob/8cab436aa1664bcd2d4543fcd56309979df0a21c/Dockerfile) seems to still rely on /data/db.sqlite3, despite postgres being in set in env.


---

## Update

Looks like it's because in pretalx-docker, there's an issue with sudo not passing docker's environment variables down to supervisord:
- https://github.com/pretalx/pretalx-docker/pull/63
