### ISSUE TITLE
Dark mode that is user-switchable and honoring system settings

### ISSUE THREAD

**Issue by colindean** [pretalx/pretalx#1560]
### Problem and impact

I tend to prefer dark themes across the board. Many web apps support the user switching between light and dark themes, while defaulting to whatever the user agent specifies (often based on time of day).

When I'm doing a lot of CFP reviews, I get a headache from the bright screen because of Pretalx's white background.

### Proposed solution / feature

Implement theming, minimally a light theme (already exists) and a dark theme (mostly just altering colors — see GitHub's dark theme for a great inspiration) that is selected based on the browser preference.

The next iteration would be a cookie-stored preference that toggles between them.

The next iteration would be something stored in the logged-in user's preference for consistency across devices/browsers.

### Context or examples

Here's a _very_ half-baked color style sheet I'm using with Stylus userstyles plugin:

```css
body {
    color: #bbb;
}

#page-content {
    background-color: #333;
}

.form-check label::before {
    background: #888;
}

.alert {
    background: #555;
}

.alert-info {
    color: #bbb;
    border-color: #193a4f;
}

.alert-info::before {
    background-color: #30698c;
}

.nav-tabs .nav-link.active,
.nav-tabs .nav-item.show .nav-link {
    color: #fff;
    background-color: #495057;
    border-color: #cadada #cadada #fff;
}

.submission-state-dropdown summary {
    background-color: #4697c9;
}

.submission-state-submitted {
    color: #fff;
    background-color: #4697c9;
}

.form-control:focus {
    color: #bbb;
    background-color: #495057;
}

.form-control {
    color: #bbb;
    background-color: #495057;
}

.submit-group {
    background-color: #3a3c3b;
}

.navbar,
aside.sidebar {
    background-color: #373737;
}

aside.sidebar a {
    color: #eee;
}

.navbar #eventDropdown .event-text .event-date,
.navbar #eventDropdown .event-text .event-organiser,
.navbar .dropdown-menu .event-text .event-date,
.navbar .dropdown-menu .event-text .event-organiser {
    color: #bbb;
}

.select2-container--default .select2-selection--multiple {
    background-color: #333;
}

.form-group .select2-container--default .select2-selection--multiple .select2-selection__choice,
.score-group .select2-container--default .select2-selection--multiple .select2-selection__choice {
    background-color: #555;
}
```

This gets about 87.5% of the way there for the review pages but needs work for everything else. My headache went away within about 10 minutes of rapidly piecing this together.
